CREATE TABLE SB_EMPLOYEE (
ID INT (10) AUTO_INCREMENT NOT NULL,
FIRST_NAME VARCHAR (20),
LAST_NAME VARCHAR (20),
PRIMARY KEY (ID)
);

CREATE TABLE SB_STUDENT (
ID INT (10) AUTO_INCREMENT NOT NULL,
NAME VARCHAR (20),
ROLL_NO VARCHAR (20),
STANDARD VARCHAR (20),
PRIMARY KEY (ID)
);